sudo: false

cache:
  directories:
    - $HOME/.composer/cache

language: php

php:
  - 7.4

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: SYMFONY_VERSION=4.0.*
    - php: 7.4
      env: SYMFONY_VERSION=5.0.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
